project:
  type: website

website:
  page-navigation: true
  title: "PSC/DATS 2102--Summer Schedule"
  description: "Homepage for PSC/DATS 2102, George Washington University."
  
  site-url: "https://dataviz-gwu.rocks"
  repo-url: "https://github.com/eteitelbaum/dataviz-summer-2023"
  repo-actions: [edit, issue]
  
  open-graph: true
  favicon: "images/dataviz-logo.png"
  twitter-card: true
  reader-mode: true
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/). üë∑üõ†Ô∏è"
    left: "&copy; Copyright 2023, [Emmanuel Teitelbaum](https://emmanuel.teitelbaum.com)"
    background: "#1F45FC"
  
  sidebar:
    background: "#1F45FC"
    logo: "images/dataviz-logo.png"
    pinned: true
    align: center
    tools:
      - icon: mortarboard-fill
        text: "Blackboard"
        href: https://blackboard.gwu.edu
      - icon: github
        href: https://classroom.github.com
        text: "Github Classroom"
      - icon: r-project # bootstrap-reboot
        href: https://posit.co/download/rstudio-desktop
        text: "RStudio Desktop"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          #- href: course-description.qmd
          #  text: Description
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: instructor.qmd
            text: Instructor
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          # - href: faq.qmd
          #   text: FAQ
      - section: "Weekly Materials"
        contents: 
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          # - href: weeks/week-3.qmd
          #   text: "Week 3"
          # - href: weeks/week-4.qmd
          #   text: "Week 4"
          # - href: weeks/week-5.qmd
          #   text: "Week 5"
          # - href: weeks/week-6.qmd
          #   text: "Week 6"
      - section: "Coding Assignments"
        contents:
          - href: assignments/coding-assignment-1.qmd
            text: "Coding Assignment 1"
          - href: assignments/coding-assignment-2.qmd
            text: "Coding Assignment 2"
          - href: assignments/coding-assignment-3.qmd
            text: "Coding Assignment 3"
          - href: assignments/coding-assignment-4.qmd
            text: "Coding Assignment 4"
          - href: assignments/coding-assignment-5.qmd
            text: "Coding Assignment 5"
      - section: "Project"
        contents:
          # - href: project/project-description.qmd
          #   text: "Description"
          - href: project/project-assignment-1.qmd
            text: "Project Assignment 1"
          - href: project/project-assignment-2.qmd
            text: "Project Assignment 2"
          - href: project/project-assignment-3.qmd
            text: "Project Assignment 3"
          - href: project/project-datasets.qmd
            text: Datasets
      - section: "Course Modules"
        contents:
          - href: modules/getting-started.qmd
            text: "Getting Started" 
          - href: modules/module-1.1.qmd
            text: "Module 1.1"
          - href: modules/module-1.2.qmd
            text: "Module 1.2"
          - href: modules/module-2.1.qmd
            text: "Module 2.1"
          - href: modules/module-2.2.qmd
            text: "Module 2.2"
          - href: modules/module-3.1.qmd
            text: "Module 3.1"
          - href: modules/module-3.2.qmd
            text: "Module 3.2"
          - href: modules/module-4.1.qmd
            text: "Module 4.1"
          - href: modules/module-4.2.qmd
            text: "Module 4.2"
          - href: modules/module-5.1.qmd
            text: "Module 5.1"
          - href: modules/module-5.2.qmd
            text: "Module 5.2"
          # - href: modules/module-6.1.qmd
          #   text: "Module 6.1"
          # - href: modules/module-6.2.qmd
          #   text: "Module 6.2"
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
freeze: auto
editor: source

